import turtle

turtle.Screen().bgcolor("black")
v=turtle.Turtle()
v.speed(10)
v.pensize(12)
v.penup()

def draw_circle():
    v.setposition(0,-290)
    v.pendown()
    v.begin_fill()
    v.color('red')
    v.pencolor("white")
    v.circle(300)
    v.end_fill()
    v.penup()

def draw_circle2():
    v.pensize(2)
    v.setposition(0,-220)
    v.pendown()
    v.begin_fill()
    v.color('black')
    v.circle(250)
    v.end_fill()
    v.penup()

def draw_A():
    v.setposition(30,-110)
    v.pendown()
    v.begin_fill()
    v.color('red')
    v.pensize(10)
    v.pencolor("white")
    v.forward(23)
    v.backward(123)
    v.left(60)
    v.backward(220)
    v.right(60)
    v.backward(100)
    v.right(117)
    v.backward(710)
    v.right(63)
    v.backward(110)
    v.right(90)
    v.backward(510)
    v.right(90)
    v.backward(100)
    v.right(90)
    v.backward(70)
    v.end_fill()
    v.penup()

def draw_triangle():
    v.pensize(10)
    v.setposition(53,-40)
    v.pendown()
    v.begin_fill()
    v.color("black")
    v.pencolor("white")
    v.right(90)
    v.forward(100)
    v.right(115)
    v.forward(250)
    v.right(157)
    v.forward(227)
    v.end_fill()

def draw_arrow():
    v.backward(80)
    v.left(42)
    v.forward(147)
    v.right(83)
    v.forward(140)


draw_circle()
draw_circle2()
draw_A()
draw_triangle()
draw_arrow()

v.hideturtle()
turtle.done()